import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { bidService, listingService, Bid as ApiBid } from '@logistics-marketplace/shared';
export interface Bid { id:string; listingId:string; listingTitle:string; carrierName:string; amount:number; status:'Pending'|'Accepted'|'Rejected'; submittedAt:string; estimatedDelivery:string; }
interface BidsState { bids:Bid[]; currentBid:Bid|null; isLoading:boolean; error:string|null; }
const initialState:BidsState={bids:[],currentBid:null,isLoading:false,error:null};
const map=(x:ApiBid,title:string):Bid=>({id:x.id,listingId:x.listingId,listingTitle:title,carrierName:x.carrierOrgId,amount:x.proposedPriceAmount,status:x.status==='Withdrawn'?'Rejected':x.status,submittedAt:x.createdAt,estimatedDelivery:''});
const load=async()=>{const listings=await listingService.getAll();const groups=await Promise.all(listings.map(async(l)=>(await bidService.getByListing(l.id)).map((b)=>map(b,l.cargoDescription))));return groups.flat();};
export const fetchBids=createAsyncThunk('bids/fetchBids',async(_,{rejectWithValue})=>{try{return await load();}catch(error){return rejectWithValue(error instanceof Error?error.message:'Failed to fetch bids');}});
export const fetchBidById=createAsyncThunk('bids/fetchBidById',async(id:string,{rejectWithValue})=>{try{const item=(await load()).find((x)=>x.id===id);if(!item)throw new Error('Bid not found');return item;}catch(error){return rejectWithValue(error instanceof Error?error.message:'Failed to fetch bid');}});
const slice=createSlice({name:'bids',initialState,reducers:{clearCurrentBid:(s)=>{s.currentBid=null;}},extraReducers:(builder)=>{builder.addCase(fetchBids.pending,(s)=>{s.isLoading=true;s.error=null;}).addCase(fetchBids.fulfilled,(s,a:PayloadAction<Bid[]>)=>{s.isLoading=false;s.bids=a.payload;}).addCase(fetchBids.rejected,(s,a)=>{s.isLoading=false;s.error=a.payload as string;}).addCase(fetchBidById.pending,(s)=>{s.isLoading=true;s.error=null;}).addCase(fetchBidById.fulfilled,(s,a:PayloadAction<Bid>)=>{s.isLoading=false;s.currentBid=a.payload;}).addCase(fetchBidById.rejected,(s,a)=>{s.isLoading=false;s.error=a.payload as string;});}});export const {clearCurrentBid}=slice.actions;export default slice.reducer;