import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { authService, dispatchService, Dispatch as ApiDispatch, DispatchStatus } from '@logistics-marketplace/shared';
export interface Dispatch { id:string; listingId:string; listingTitle:string; origin:string; destination:string; status:'In Transit'|'Delivered'|'Delayed'|'Pending'; driver:string; vehicle:string; estimatedDelivery:string; actualDelivery?:string; }
export interface DispatchesState { dispatches:Dispatch[]; currentDispatch:Dispatch|null; isLoading:boolean; error:string|null; }
export const initialState:DispatchesState={dispatches:[],currentDispatch:null,isLoading:false,error:null};
const status=(value:DispatchStatus):Dispatch['status']=>value===DispatchStatus.Delivered?'Delivered':value===DispatchStatus.Failed?'Delayed':value===DispatchStatus.PickedUp||value===DispatchStatus.EnRoute?'In Transit':'Pending';
const map=(x:ApiDispatch):Dispatch=>({id:x.id,listingId:x.dealId,listingTitle:`Deal ${x.dealId}`,origin:'-',destination:'-',status:status(x.status),driver:x.driverId??'Chưa gán',vehicle:x.vehicleId??'Chưa gán',estimatedDelivery:x.scheduledDelivery,actualDelivery:x.actualDelivery});
const load=async()=>{const org=authService.getStoredUser()?.organizationId;if(!org)throw new Error('Carrier organization is required');return (await dispatchService.getForCarrier(org)).map(map);};
export const fetchDispatches=createAsyncThunk('dispatches/fetchDispatches',async(_,{rejectWithValue})=>{try{return await load();}catch(error){return rejectWithValue(error instanceof Error?error.message:'Failed to fetch dispatches');}});
export const fetchDispatchById=createAsyncThunk('dispatches/fetchDispatchById',async(id:string,{rejectWithValue})=>{try{const item=(await load()).find((x)=>x.id===id);if(!item)throw new Error('Dispatch not found');return item;}catch(error){return rejectWithValue(error instanceof Error?error.message:'Failed to fetch dispatch');}});
const slice=createSlice({name:'dispatches',initialState,reducers:{clearCurrentDispatch:(s)=>{s.currentDispatch=null;}},extraReducers:(builder)=>{builder.addCase(fetchDispatches.pending,(s)=>{s.isLoading=true;s.error=null;}).addCase(fetchDispatches.fulfilled,(s,a:PayloadAction<Dispatch[]>)=>{s.isLoading=false;s.dispatches=a.payload;}).addCase(fetchDispatches.rejected,(s,a)=>{s.isLoading=false;s.error=a.payload as string;}).addCase(fetchDispatchById.pending,(s)=>{s.isLoading=true;s.error=null;}).addCase(fetchDispatchById.fulfilled,(s,a:PayloadAction<Dispatch>)=>{s.isLoading=false;s.currentDispatch=a.payload;}).addCase(fetchDispatchById.rejected,(s,a)=>{s.isLoading=false;s.error=a.payload as string;});}});export const {clearCurrentDispatch}=slice.actions;export default slice.reducer;